USE_PROTECTED_MAPPING = "USE_PROTECTED_MAPPING"
NAMESPACE = "kube-system"
CM_NAME = "aws-auth"
PROTECTED_MAPPING = "aws-auth-protected-mappings"
CRD_GROUP = "tier.app"
CRD_NAME = "awsauthmappings"
CRD_VERSION = "v1"
CRD_KIND = "AwsAuthMapping"
