
{{- if .Values.prometheus.enabled -}}
{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
      app: prometheus-operator
      release: prometheus-operator
  name: {{ include "aws-auth-operator.name" . }}-rules
spec:
  groups:
  - name: ./alert.rules
    rules:
  {{- range .Values.alerts.rules }}
    - alert: {{ .alert | quote }}
      expr: {{ .expr | quote }} 
      for: {{ .for | quote }} 
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}