apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-auth-operator.name" . }}
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "aws-auth-operator.name" . }}
    helm.sh/chart: {{ include "aws-auth-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
