
releases:
  - name: aws-auth-operator
    chart: aws-auth-operator
    namespace: aws-auth-operator
    wait: true
    timeout: 120
    values:
      - image:
          tag: '{{ env "IMAGE_TAG" | default "latest-master" }}'
          repository: '{{ env "ECR_REPOSITORY_URL" }}'